= clublist - Club Membership List

Track members for a small non-profit club.

This shows off some basic functionality of JPA and DeltaSpike Data in a JSF environment.

== Deployment

. Copy config-sample.properties to config.properties, change the name in the orgName property
in this file from 'Sample Club' to your organization's name (keep it short).
. Set up a JTA datasource in your app server
. Change persistence.xml from the in-memory H2 to the JTA datasource
. Setup the deployment as needed (e.g., edit jboss-deployment.xml)
. Create a user in the role of club_exec in your app server.
. Deploy (e.g., mvn wildfly:deploy if you use JBoss WildFly).
. Enjoy!

== ToDo

Here are some things that should be added. https://github.com/IanDarwin/clublist[Fork this project on GitHub] and send pull requests when you get one working!

. Search with 'Like' method in DS Data
. Maybe allow members to update their own record (only!)
Probably requires moving to app-managed security since you already have a record for each person.
. "Position" should be a relationship to another Entity, with a dropdown chooser.
Note that this will need its own list-detail mechanism to manage the list of Positions!
. There should be a "Membership Type" (student, senior, couple/family, etc). This should be a relationship to another Entity, with a dropdown (as above).
. A confirmation (p:dialog?) on the Edit->Delete button would be a good idea.
. Implement the Mailing List page. For the simple form, use JavaMail.
. Implement the Print Member Badge/Label page.
. Even though people should not use spreadsheets for database work, you will probably
be pressured to implement the "Export" capability. 
You will need http://poi.apache.org/[Apache POI] for this.
. Refactor Home object to merge w/ darwinsys-ee EntityHome
