= clublist - Club Membership List

Track members for a small non-profit club.

This shows off some basic functionality of JPA and DeltaSpike Data in a JSF environment.

== Deployment

. Copy config-sample.properties to config.properties, change the name in the orgName property
in this file from 'Sample Club' to your organization's name (keep it short).
. Setup the datasource in your app server
. Setup the deployment as needed (e.g., edit jboss-deployment.xml)
. Create a user in the role of club_exec in your app server.
. Deploy (e.g., mvn wildfly:deploy if you use JBoss WildFly).
. Enjoy!

== ToDo

Security: Maybe allow members to update their own record (only!)

Use redirect after editing to really go back to the List page.

"Position" should be a relationship to another Entity, with a dropdown chooser.

"Membership Type" should be a relationship to another Entity, with a dropdown.

Search with 'Like' method in DS Data

A confirmation (p:dialog?) on the Edit->Delete button would be a good idea.

Implement the Mailing List page.

Implement the Print Member Badge/Label page.

Even though people should not use spreadsheets for database work, you will probably
be pressured to impelement the "Export" capability. You will need Apache POI for this.

Refactor Home object to merge w/ darwinsys-ee EntityHome
